OS:
  Sanitize:
    "F41":
      TYPE: scripted
      IMAGE: fedora41
      BUILD_SCRIPT: bareos/devtools/build-and-test-with-sanitize.sh
      FINISH_SCRIPT: CD/sanitize/finish-sanitize.sh
      ARCH:
        - x86_64
