JENKINS_TESTTYPES:
  - bareos-client-only+bareos-universal-client+bareos-postgresql
  - univention-bareos

OS:
  EL:
    "8":
      TYPE: rpm
      IMAGE: rhel8
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, Stream, RHEL ]
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos

  win:
    cross:
      TYPE: win
      STAGES:
        - win-32-release
        - win-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-10-32
         - windows-10-64
