JENKINS_TESTTYPES:
  - bareos-client-only
  - bareos-postgresql
  - univention-bareos
  - bareos-universal-client

OS:
  ULC_deb:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: debian9.0
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      ARCH:
        - i586
        - x86_64
      PROJECTPACKAGES:
        i586:
          - bareos
        x86_64:
          - bareos

  xUbuntu:
    "22.04":
      TYPE: deb
      IMAGE: "ubuntu22.04"
      ARCH:
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos
    "20.04":
      TYPE: deb
      IMAGE: "ubuntu20.04"
      ARCH:
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos

    "18.04":
      TYPE: deb
      IMAGE: "ubuntu18.04"
      ARCH:
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos

  openSUSE:
    "Leap_15.4":
      TYPE: rpm
      IMAGE: opensuse-leap154
      ARCH:
      - x86_64
      PROJECTPACKAGES:
       x86_64:
          - bareos
          - python-bareos

    "Leap_15.3":
      TYPE: rpm
      IMAGE: opensuse-leap153
      ARCH:
      - x86_64
      PROJECTPACKAGES:
       x86_64:
          - bareos
          - python-bareos

    "Leap_15.2":
      TYPE: rpm
      IMAGE: opensuse-leap152
      ARCH:
      - x86_64
      PROJECTPACKAGES:
       x86_64:
          - bareos
          - python-bareos

  Univention:
    "4.4":
      TYPE: deb
      IMAGE: univention4.4
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - python-bareos


  SLE:
    "15_SP4":
      TYPE: rpm
      IMAGE: sle154
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
    "15_SP3":
      TYPE: rpm
      IMAGE: sle153
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
    "15_SP2":
      TYPE: rpm
      IMAGE: sle152
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
    "12_SP5":
      TYPE: rpm
      IMAGE: sles12sp5
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos

  RHEL:
    "8":
      TYPE: rpm
      IMAGE: rhel8
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos
    "7":
      TYPE: rpm
      IMAGE: rhel7
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos

  Fedora:
    "36":
      TYPE: rpm
      IMAGE: fedora36
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
    "35":
      TYPE: rpm
      IMAGE: fedora35
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
    "34":
      TYPE: rpm
      IMAGE: fedora34
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
  Debian:
    "11":
      TYPE: deb
      IMAGE: "debian11"
      ARCH:
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos
    "10":
      TYPE: deb
      IMAGE: "debian10"
      ARCH:
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos
    "9.0":
      TYPE: deb
      IMAGE: "debian9.0"
      ARCH:
        - i586
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos
        i586:
           - bareos
           - bareos-webui
           - python-bareos

  EL:
    "9":
      TYPE: rpm
      IMAGE: centos9
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos
    "8":
      TYPE: rpm
      IMAGE: rocky8
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos
  CentOS:
    "7":
      TYPE: rpm
      IMAGE: centos7
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos

  FreeBSD:
    "12.3":
      TYPE: freebsd
      ARCH:
        - amd64
      PROJECTPACKAGES:
        amd64:
           - bareos-freebsd
    "13.1":
      TYPE: freebsd
      ARCH:
        - amd64
      PROJECTPACKAGES:
        amd64:
           - bareos-freebsd

  MacOS:
    "10.13.6":
      TYPE: macos
      ARCH:
        - x64
      PROJECTPACKAGES:
        x64:
  Solaris:
    "11.4":
      TYPE: solaris
      ARCH:
        - i386
        - sparc
      PROJECTPACKAGES:
        i386:
           - bareos
        sparc:
           - bareos

  win:
    cross:
      TYPE: win
      STAGES:
        - win-32-release
        - win-64-release
      ARCH:
       - x86_64
      PROJECTPACKAGES:
        x86_64:
           - mingw-debugsrc
           - mingw32-winbareos
           - mingw64-winbareos
           - winbareos-nsi
           - winbareos-opsi
      WINVERSIONS:
         - windows-10-32
         - windows-10-64
