JENKINS_TESTTYPES:
  - bareos-client-only+bareos-universal-client+bareos-postgresql
  - univention-bareos

OS:
  Sanitize:
    "F37":
      TYPE: scripted
      IMAGE: fedora37
      BUILD_SCRIPT: bareos/devtools/build-and-test-with-sanitize.sh
      FINISH_SCRIPT: CD/sanitize/finish-sanitize.sh
      ARCH:
        - x86_64
  ULC_deb:
    "OpenSSL_1.1":
      TYPE: scripted
      IMAGE: "ubuntu18.04"
      BUILD_SCRIPT: CD/deb/build-ulc.sh
      FINISH_SCRIPT: CD/deb/finish-ulc.sh
      ARCH:
        - x86_64

  xUbuntu:
    "22.04":
      TYPE: deb
      IMAGE: "ubuntu22.04"
      ARCH:
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos
    "20.04":
      TYPE: deb
      IMAGE: "ubuntu20.04"
      ARCH:
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos

  SUSE:
    "15":
      TYPE: rpm
      IMAGE: sle154
      CUSTOM_TEST_IMAGES: [ SLE-15_SP3, SLE-15_SP4, openSUSE-Leap_15.3, openSUSE-Leap_15.4 ]
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
  SLE:
    "12_SP5":
      TYPE: rpm
      IMAGE: sles12sp5
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos

  Fedora:
    "37":
      TYPE: rpm
      IMAGE: fedora37
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
    "36":
      TYPE: rpm
      IMAGE: fedora36
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - python-bareos
  Debian:
    "11":
      TYPE: deb
      IMAGE: "debian11"
      ARCH:
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos
    "10":
      TYPE: deb
      IMAGE: "debian10"
      CUSTOM_TEST_IMAGES: [ Debian, "Univention-5.0" ]
      ARCH:
        - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-webui
           - bareos-vmware
           - python-bareos

  EL:
    "9":
      TYPE: rpm
      IMAGE: rhel9
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, Stream, RHEL ]
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos
    "8":
      TYPE: rpm
      IMAGE: rhel8
      CUSTOM_TEST_IMAGES: [ Rocky, Alma, Oracle, Stream, RHEL ]
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos
    "7":
      TYPE: rpm
      IMAGE: rhel7
      CUSTOM_TEST_IMAGES: [ CentOS, RHEL ]
      ARCH:
      - x86_64
      PROJECTPACKAGES:
        x86_64:
           - bareos
           - bareos-vmware
           - python-bareos

  FreeBSD:
    "12.3":
      TYPE: freebsd
      ARCH:
        - amd64
      PROJECTPACKAGES:
        amd64:
           - bareos-freebsd
    "13.1":
      TYPE: freebsd
      ARCH:
        - amd64

  MacOS:
    "10.13.6":
      TYPE: macos
      ARCH:
        - x64

  Solaris:
    "11.4":
      TYPE: solaris
      ARCH:
        - i386

  win:
    cross:
      TYPE: win
      STAGES:
        - win-32-release
        - win-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-10-32
         - windows-10-64
