OS:
  Fedora:
    "40":
      TYPE: rpm
      IMAGE: fedora40
      ARCH:
      - x86_64
  win:
    native:
      TYPE: win-native
      STAGES:
        - win-native-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-11-64
    cross:
      TYPE: win
      STAGES:
        - win-64-release
      ARCH:
       - x86_64
      WINVERSIONS:
         - windows-10-64
