---
# quality gates to configure Jenkins build pipeline
coverage:
  lines:
    healthy: 70
    unhealthy: 38
    unstable: 40

default:
  ctest_unstable: 0
  warnings_unhealthy: 1
  warnings_healthy: 0

win-native-64-release:
  ctest_unstable: 75
  warnings_unhealthy: 222
  warnings_healthy: 199
