#!/bin/bash
set -e
set -o pipefail
set -u
#
# Do a full restore from an archive job.
#

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
messages
@$out $tmp/setup.out
setdebug level=100 storage=File
status director
status client
status storage=File
wait
messages
@$out $tmp/jobs.out
list jobs
@$out $tmp/should-work.out
update jobid=1 jobtype=A
restore archive client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores select all done yes
wait
messages
update jobid=1 jobtype=B
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

# check the most current jobs list form $tmp/jobs.out and check that it is
# indeed a backup
if ! grep "1 | backup-bareos-fd" "$tmp/jobs.out" | tail -n 1 | grep "| B" > /dev/null; then
    echo "Job 1 has to always be a backup job at the start of a test."
    exit 5
fi

expect_grep "Start Restore Job" \
	    "$tmp/should-work.out" \
	    "Required restore job was not started."

check_restore_diff "${BackupDirectory}"
end_test
