#!/bin/bash
set -e
set -o pipefail
set -u
#
# restore some a directory from archives
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

dir="$(pwd)/tmp/data/build/src/tests"
if [[ -d "$tmp/bareos-restores/$dir" ]]; then
    rm -r "$tmp/bareos-restores/$dir"
fi
cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
setdebug level=100 storage=File
@$out /tmp/log1.out
status director
status client
status storage=File
update jobid=1 jobtype=A
@$out $tmp/restore-dir-from-archive.out
restore archive
11
1
$dir

yes
wait
update jobid=1 jobtype=B
messages
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

expect_grep "Start Restore Job" \
	    "$tmp/restore-dir-from-archive.out" \
	    "The restore job was not started."

check_restore_diff "$dir"
end_test
