#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2021-2023 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

set -x

#shellcheck source=../environment.in
. ./environment
. "${rscripts}/functions"

print_debug "drop database \"${db_name}\" (${DBTYPE})"
"${scripts}/drop_bareos_database" "${DBTYPE}" >/dev/null 2>&1

print_debug "creating database \"${db_name}\" (${DBTYPE})"
"${scripts}/create_bareos_database" "${DBTYPE}" >/dev/null 2>&1
"${scripts}/make_bareos_tables" "${DBTYPE}" >/dev/null 2>&1
"${scripts}/grant_bareos_privileges" "${DBTYPE}" >/dev/null 2>&1

if lsof="$(command -v lsof)"; then
  for port in $BASEPORT $BAREOS_DIRECTOR_PORT $BAREOS_STORAGE_PORT \
    $BAREOS_STORAGE2_PORT $BAREOS_FD_PORT $MINIO_PORT; do
    if pid=$("${lsof}" -ti "tcp:$port"); then
      print_debug "Killing process listening on $port with PID $pid"
      kill -9 "$pid"
    fi
  done
fi

# extend local systemtests
localsetup="testrunner.d/setup"
if [ -f ${localsetup} ]; then
  echo "localsetup is ${localsetup}"
  ${localsetup}
fi

exit 0
