#!/bin/bash
set -e
set -o pipefail
set -u
#
# Run a simple backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
delete jobid=1-1000
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
restore client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores \
	file=$(pwd)/tmp/data/build/src/tests/Makefile \
	done yes
run job=$JobName yes
status director
status client
status storage=File
@$out $tmp/should-fail.out
wait
messages
restore archive client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores \
	file=$(pwd)/tmp/data/build/src/tests/Makefile \
	done yes
update jobid=1 jobtype=A
wait
messages
@$out $tmp/should-work.out
restore archive client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores \
	file=$(pwd)/tmp/data/build/src/tests/Makefile \
	done yes
wait
messages
@$out $tmp/restore-from-selected-job.out
restore archive
12
1
mark $(pwd)/tmp/data/build/src/tests/Makefile.in
done
yes
wait
messages
@$out $tmp/restore-from-list-and-time.out
restore archive
8
$(( $(date +%Y) + 1))
2025
$(pwd)/tmp/data/build/src/tests/bbatch.c

yes
wait
messages
wait
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

expect_not_grep "Try" \
		"$tmp/log1.out" \
		"Error: Should not ask user to try restoring from \
		archives if no archives exist."

expect_grep "No database record found for:" \
	    "$tmp/should-fail.out" \
	    "Expected failure; found success"

expect_grep "1 file selected to be restored." \
	    "$tmp/should-work.out" \
	    "Expected success; found failure"

check_two_logs
if ! cmp -s "$tmp/bareos-restores/$(pwd)/tmp/data/build/src/tests/Makefile" \
     "$(pwd)/tmp/data/build/src/tests/Makefile"; then
    exit 2
fi

if ! cmp -s "$tmp/bareos-restores/$(pwd)/tmp/data/build/src/tests/Makefile.in" \
     "$(pwd)/tmp/data/build/src/tests/Makefile.in"; then
    exit 3
fi

if ! cmp -s "$tmp/bareos-restores/$(pwd)/tmp/data/build/src/tests/bbatch.c" \
     "$(pwd)/tmp/data/build/src/tests/bbatch.c"; then
    exit 4
fi
#check_restore_diff "${BackupDirectory}"
end_test
