#!/bin/bash
set -e
set -o pipefail
set -u
#
# restore some single files from archives
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
setdebug level=100 storage=File
@$out /tmp/log1.out
status director
status client
status storage=File
wait
messages
update jobid=1 jobtype=A
@$out $tmp/should-work.out
restore archive client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores \
	file=$(pwd)/tmp/data/build/src/tests/Makefile \
	done yes
messages
wait
@$out $tmp/restore-from-selected-job.out
restore archive
12
1
mark $(pwd)/tmp/data/build/src/tests/Makefile.in
done
yes
wait
messages
@$out $tmp/restore-from-list-and-time.out
restore archive
8
$(( $(date +%Y) + 1))
2025
$(pwd)/tmp/data/build/src/tests/bbatch.c

yes
wait
messages
wait
@# restore old job type
update jobid=1 jobtype=B
wait
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

expect_grep "1 file selected to be restored." \
	    "$tmp/should-work.out" \
 	    "Expected success; found failure"

check_two_logs
if ! cmp -s "$tmp/bareos-restores/$(pwd)/tmp/data/build/src/tests/Makefile" \
     "$(pwd)/tmp/data/build/src/tests/Makefile"; then
    exit 2
fi

if ! cmp -s "$tmp/bareos-restores/$(pwd)/tmp/data/build/src/tests/Makefile.in" \
     "$(pwd)/tmp/data/build/src/tests/Makefile.in"; then
    exit 3
fi

if ! cmp -s "$tmp/bareos-restores/$(pwd)/tmp/data/build/src/tests/bbatch.c" \
     "$(pwd)/tmp/data/build/src/tests/bbatch.c"; then
    exit 4
fi
#check_restore_diff "${BackupDirectory}"
end_test
