#!/bin/bash
set -e
set -o pipefail
set -u
#
# Run a simple backup
#   then restore it.
#
TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out /dev/null
messages
@$out $tmp/log1.out
setdebug level=100 storage=File
run job=$JobName yes
status director
status client
status storage=File
wait
update jobid=1 jobtype=A
messages
@$out $tmp/wrong-restore.out
@#
@# Try restoring from normal backups
@#
wait
messages
restore client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores select all done yes
wait
messages
@#
@# now do a restore
@#
@$out $tmp/log2.out
restore archive client=bareos-fd fileset=SelfTest where=$tmp/bareos-restores select all done yes
wait
messages
quit
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

expect_grep "No Full backup" \
	    "$tmp/wrong-restore.out" \
	    "Restore should not be able to restore archives."

expect_grep "Start Restore Job" \
	    "$tmp/log2.out" \
	    "Required restore job was not started."

check_two_logs
check_restore_diff "${BackupDirectory}"
end_test
