#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2025-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

#
# Check that the stored correctly handles the weird bsr.
#

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${NULL_DEV}
messages
@$out ${LOGHOME}/restore.out
restore client=bareos-fd bootstrap="${LOGHOME}/bootstrap.out" select all done yes
wait
messages
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

expect_grep "Restore OK" \
	    "${LOGHOME}/restore.out" \
	    "Restore job was not successful"

check_restore_diff "${BackupDirectory}"

expect_grep "${INCRCONTENT}" \
            "${RestoreDirectory}/$(realpath ${FILE})" \
            "Did not restore file correctly"
end_test
