#!/bin/bash

#   BAREOS® - Backup Archiving REcovery Open Sourced
#
#   Copyright (C) 2025-2025 Bareos GmbH & Co. KG
#
#   This program is Free Software; you can redistribute it and/or
#   modify it under the terms of version three of the GNU Affero General Public
#   License as published by the Free Software Foundation and included
#   in the file LICENSE.
#
#   This program is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#   Affero General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
#   02110-1301, USA.

#
# We want to create a chain of backups 1 (Full), 2 (Diff), 3 (Incr),
# so that jobs 1 & 3 occupy the same volume, but 2 is on a different volume
#

set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

FILESIZE="3M"

start_test

#### CREATE FULL ####

cat <<< "${FULLCONTENT}" > "${FILE}"
truncate -s "${FILESIZE}" "${FILE}"

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${NULL_DEV}
messages
@$out ${LOGHOME}/label-volumes.out
label volume=TestVolume001 storage=File pool=File
label volume=TestVolume002 storage=File pool=File
update volstatus=Used volume=TestVolume002
@$out ${LOGHOME}/create-full.out
run job=$JobName level=Full yes
status director
status client
status storage=File
wait
status director
status client
status storage=File
messages
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

#### CREATE DIFF ####

cat <<< "${DIFFCONTENT}" > "${FILE}"
truncate -s "${FILESIZE}" "${FILE}"

cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${LOGHOME}/switch-vol-1.out
update volstatus=Append volume=TestVolume002
update volstatus=Used volume=TestVolume001
@$out ${LOGHOME}/create-diff.out
run job=$JobName level=Differential yes
status director
status client
status storage=File
wait
status director
status client
status storage=File
messages
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

#### CREATE INCR ####

cat <<< "${INCRCONTENT}" > "${FILE}"
truncate -s "${FILESIZE}" "${FILE}"
cat <<END_OF_DATA >"$tmp/bconcmds"
@$out ${LOGHOME}/switch-vol-2.out
update volstatus=Append volume=TestVolume001
@$out ${LOGHOME}/create-incr.out
run job=$JobName level=Incremental yes
status director
status client
status storage=File
wait
status director
status client
status storage=File
messages
END_OF_DATA

run_bconsole

check_for_zombie_jobs storage=File

expect_grep "Backup OK" \
	    "${LOGHOME}/create-full.out" \
	    "Full was not created correctly."
expect_grep "Backup OK" \
	    "${LOGHOME}/create-diff.out" \
	    "Diff was not created correctly."
expect_grep "Backup OK" \
	    "${LOGHOME}/create-incr.out" \
	    "Incr was not created correctly."

end_test
