#!/bin/bash
set -e
set -o pipefail
set -u

TestName="$(basename "$(pwd)")"
export TestName

JobName=backup-bareos-fd

#shellcheck source=../environment.in
. ./environment

#shellcheck source=../scripts/functions
. "${rscripts}"/functions

start_test

rm -f "$tmp/forcebackup-backup.out" 

cat <<END_OF_DATA >$tmp/bconcmds
@$out $tmp/prepare-backup.out
messages
setdebug client=bareos-fd level=130 trace=1
run job=$JobName fileset=PluginSinceTime level=Full yes
wait
run job=$JobName fileset=PluginCheckChanges level=Full yes
wait
messages
@$out $tmp/sincetime-backup.out
run job=$JobName fileset=PluginSinceTime level=Incremental yes
wait
messages
@$out $tmp/checkchanges-backup.out
run job=$JobName fileset=PluginCheckChanges level=Incremental yes
wait
messages
END_OF_DATA

run_bconsole
check_for_zombie_jobs storage=File

expect_grep "FD Files Written:       1" \
            "$tmp/sincetime-backup.out" \
            "Incremental with SinceTime=0 did not backup file!"

expect_grep "FD Files Written:       1" \
            "$tmp/checkchanges-backup.out" \
            "Incremental with CheckChanges=false did not backup file!"

end_test
